## COP Arbitrage Base Model

#### All that's going on here:
1. Aggregating OpenEI energy use with TMY3 temperature data for all hours year long on selected locations
2. Sum daily energy load for DHW and Heating
3. Build 4 models of estimated annual thermal energy need:
    - Heat Pump only
    - Heat Pump with storage
        - overly optimistic, takes best COP over 24hr period and purchases all at that moment (assumes infinite storage capacity and heat pump capacity)
        - we get docked here in some locations because of standby losses associated with thermal storage (assuming 4%)
    - Resistive Heating
        - 98% efficient
    - Natural Gas
        - 85% efficient
4. Heat pump performance curves are based on the curve generated below based on SANDEN reported numbers.
    - operating on a CO2 refrigeration cycle
    - EWT of 50F (which is not realistic for thermal storage, likely EWT around room temp)



combine data from early Sensiblle Heat storage calcs and more recent findEnergyUse to map the benefit of thermal storage across America.

In [1]:
import pandas as pd
import datetime
import os
from glob import glob
import plotly.graph_objects as go
import plotly.express as px
from scipy import optimize
import numpy as np
import matplotlib.pyplot as plt


# globals
COE = 0.2

In [9]:


def create_df(finishString, shiftTime):
    
    update = []
    ### WILL NEED TO UDPATE PATH
    directory = os.path.join("c:\\", "/Users/voncronic/Desktop/OL_data_for_watts_personal/data")
    for root,dirs,files in os.walk(directory):
        for file in files:
            if file.endswith(finishString):
                #print (file)

                li = file.split('_')
                city = li[2].split('.')[0]
                tmy3 = int(li[2].split('.')[-1])
                print (tmy3)
                print(city)
                path = "./data/" + file
                current = pd.read_csv(path)
                cleanDF = clean_datetime(current)
                
                tmyFileName = str(tmy3) + 'TYA.csv'
                
                
                tempData = pd.read_csv('./data/' + tmyFileName, skiprows=[0])
                tempList = tempData['Dry-bulb (C)'].tolist()
                cleanDF['DRY BULB (C)'] = tempList

                # heatNeed = get_gas_use(cleanDF, shiftTime)
                heatNeed = 1
                peakLoad = cleanDF['Gas:Facility [kW](Hourly)'].max() # this could be the size of HP
                
                # COP FUNCTION (from another slide) currently 150F SANDEN
                params = [3.61675824e+00,  6.29945053e-02, -1.18131867e-03]
                cleanDF['COP'] = (params[0] + params[1]*cleanDF['DRY BULB (C)'] + params[2]*cleanDF['DRY BULB (C)']**2 )
                
                cleanDF['HP_need'] = cleanDF['Gas:Facility [kW](Hourly)'] / cleanDF['COP']
                dailyMax = cleanDF.resample('24H').max()
                dailySum = cleanDF.resample('24H').sum()
                HP_max = dailySum['Gas:Facility [kW](Hourly)'].max() / 24
                sumAndMax = dailySum.join(dailyMax, rsuffix='_max')
                
                
                
                sumAndMax['storage_need'] = (sumAndMax['Gas:Facility [kW](Hourly)'] / sumAndMax['COP_max']) *1.04
                
                annualStorage = sumAndMax['storage_need'].sum()
                annualHP = sumAndMax['HP_need'].sum()
                annualResistive = sumAndMax['Gas:Facility [kW](Hourly)'].sum() / 0.98
                annualNG = sumAndMax['Gas:Facility [kW](Hourly)'].sum() / 0.85
                
                update.append([tmy3, city,peakLoad,HP_max, annualStorage, annualHP, annualResistive, annualNG])
                
    return pd.DataFrame(update, columns=['tmy3', 'city','peakLoad','HP_max', 'annualStorage', 'annualHP', 'annualResistive', 'annualNG'])

def to_C(F):
    C = (F-32) * (5/9)
    return (C)

def clean_datetime(df):
    pat = '(?P<month>\d{2})/(?P<day>\d{2})  (?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2})'
    exp = df['Date/Time'].str.extract(pat,expand=True)
    exp['hour'] = exp['hour'].replace(24,0)
    exp['year'] = 2014

    df = df.set_index(pd.to_datetime(exp))

    return df

In [10]:
new = create_df('LOW.csv', 12)
new['percentLess'] = new['annualStorage'] / new['annualHP']
new

724699
Boulder-Broomfield-Jefferson
723085
Norfolk
724463
Kansas
725090
Boston-Logan
722110
Tampa
702730
Anchorage
726185
Augusta
726410
Madison-Dane
722280
Birmingham
726797
Bozeman-Gallatin
726620
Rapid
727935
Seattle-Boeing
722784
Phoenix-Deer
724930
Oakland
726185
Augusta

,tmy3,city,peakLoad,HP_max,annualStorage,annualHP,annualResistive,annualNG,percentLess
0,724699,Boulder-Broomfield-Jefferson,8.119554,5.806781,3408.093166,3654.404529,13235.880589,15260.191738,0.932599
1,723085,Norfolk,3.982023,2.699524,786.909506,794.275907,3124.941809,3602.874085,0.990726
2,724463,Kansas,5.509993,3.455536,1260.276325,1299.576376,4815.122744,5551.553282,0.969759
3,725090,Boston-Logan,9.397890,6.313666,3818.716785,3911.249460,14574.142476,16803.128972,0.976342
4,722110,Tampa,0.342938,0.110122,203.724420,197.907079,886.871948,1022.511187,1.029394
5,702730,Anchorage,10.208369,7.825157,6850.853193,7212.559249,22748.856752,26228.093667,0.949851
6,726185,Augusta,11.392054,8.377955,5423.081672,5934.302805,18578.099247,21419.455603,0.913853
7,726410,Madison-Dane,12.243027,8.327188,5543.696086,6485.263069,18636.869266,21487.213977,0.854814
8,722280,Birmingham,4.286480,2.548362,646.899604,679.802868,2653.679215,3059.536036,0.951599
9,726797,Bozeman-Gallatin,12.359991,8.629339,4991.512594,5944.855368,17674.194533,20377.306639,0.839636
10,726620,Rapid,10.556124,7.444299,4695.899119,5256.517930,17004.359791,19605.026583,0.893348
11,727935,Seattle-Boeing,4.452577,3.258255,2120.954571,2105.977138,8699.016832,10029.454701,1.007112
12,722784,Phoenix-Deer,1.965678,0.884682,994.720784,979.920841,4308.585620,4967.545774,1.015103
13,724930,Oakland,2.807151,1.662604,1433.183997,1416.675022,6094.684521,7026.812742,1.011653
14,726185,Augusta,11.392054,8.377955,5423.081672,5934.302805,18578.099247,21419.455603,0.913853

In [11]:

newHigh = create_df('HIGH.csv', 12)
newHigh['percentLess'] = newHigh['annualStorage'] / newHigh['annualHP']
newHigh['savings'] = 
newHigh

SyntaxError: invalid syntax (<ipython-input-11-abcbfa408a29>, line 3)

### Request is:

We need to generate a realistic equation for calculating COP based on EWT and LWT, given some GPM and T-s diagram for the refrigerant used.